services:

  eureka-server:
    image: tmalli834/eureka-server:1.0
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  config-server:
    image: tmalli834/config-server:1.0
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/config-repo
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservices-network

  user-service:
    image: tmalli834/user-service:1.0
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - microservices-network

  order-service:
    image: tmalli834/order-service:1.0
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - microservices-network

  product-service:
    image: tmalli834/product-service:1.0
    container_name: product-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - microservices-network

  api-gateway:
    image: tmalli834/api-gateway:1.0
    container_name: api-gateway
    ports:
      - "8090:8080"
    depends_on:
      - eureka-server
      - config-server
      - user-service
      - order-service
      - product-service
      - redis
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
